### PR TITLE
[PKG-2957] rdkit 2023.03.3  :snowflake:

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Changelog: https://github.com/rdkit/rdkit/releases
License: https://github.com/rdkit/rdkit/blob/master/license.txt
Requirements: 
- https://github.com/rdkit/rdkit/blob/master/Docs/Book/Install.md
- https://www.rdkit.org/docs/Install.html#how-to-build-from-source-with-conda
- https://github.com/rdkit/rdkit/blob/Release_2023_03_3/CMakeLists.txt

Actions:
1. Disable `cairo` support `-D RDK_BUILD_CAIRO_SUPPORT=OFF` in build scripts and add a comment
2. Remove skipping `py>310` as we already have `py-boost` with **py311** support, but not for win64 yet because boost v1.82 raises an error `%PREFIX%\Library\include\boost/container_hash/hash.hpp(629): error C2668: 'boost::hash_value': ambiguous call to overloaded function`. At the same time v1.73 works fine.
3. Remove `cairo` from `host` and `run`, and `pycairo` from `run` (`cairo` was needed to generate high-quality PNGs for structure depiction, see https://www.rdkit.org/docs/Install.html?highlight=cairo#recommended-extras but we disable it intentionally)
4. Remove ignore_run_exports with `pixman` as we removed `cairo`.
5. Add pinning 1.73 for boost-cpp, libboost, py-boost on win, and 1.82 for libboost and py-boost on unix
6. Add rdkit.Chem.Draw to test/import to check if it works because there were classes for cairo support, see https://www.rdkit.org/docs/source/rdkit.Chem.Draw.rdMolDraw2D.html#rdkit.Chem.Draw.rdMolDraw2D.MolDraw2DCairo

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
Hm, an error on `osx-64`:
`/private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_16i0bc3hu5/croot/rdkit_1696319075388/work/Code/RDGeneral/RDValue-taggedunion.h:46:10: fatal error: 'boost/lexical_cast.hpp' file not found`

I've rerun a workflow on Prefect

File: recipe/meta.yaml [hunk 1]
```diff
@@ -9,21 +9,18 @@ package:
...
-  sha256: bb43216b075b93b767e6cbaecd5e95d087da887bcdc51afd36d940d8bd9f9819
+  sha256: bdbf9a2e6988526bfeb8c56ce3cdfe2998d60ac289078e2215374288185e8c8d
 
 build:
   number: 0
   # We skip s390x because it's not supported.
-  skip: True # [s390x]
-  # py-boost hasn't been built for Python 3.11 yet.
-  skip: True # [py<37 or py>310]
+  # py-boost 1.73 isn't available for Python 3.11 on Windows.
```
Comment (M-Waszkiewicz-Anaconda) [inline recipe/meta.yaml]: can we try with latest Visual Studio ( is it 2019, I suppose ) ?

Comment (skupr-anaconda) [reply recipe/meta.yaml]: It's a good suggestion. I'll try

**Comment by skupr-anaconda** [comment]
@M-Waszkiewicz-Anaconda A new error with vs2019:
```
    conda_build.exceptions.OverLinkingError: overlinking check failed

    ['  ERROR (rdkit,Lib/site-packages/rdkit/Chem/Scaffolds/rdScaffoldNetwork.pyd): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitFileParsers.dll): $RPATH/boost_iostreams.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitFilterCatalog.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitmaeparser.dll): $RPATH/boost_iostreams.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitSubstructLibrary.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitScaffoldNetwork.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Lib/site-packages/rdkit/Chem/rdSubstructLibrary.pyd): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitGraphMol.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitScaffoldNetwork.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitmaeparser.dll): $RPATH/boost_iostreams.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitRDStreams.dll): $RPATH/boost_iostreams.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitRDStreams.dll): $RPATH/boost_iostreams.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Lib/site-packages/rdkit/Chem/rdChemReactions.pyd): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitSubstructLibrary.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Lib/site-packages/rdkit/Chem/rdfiltercatalog.pyd): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitChemReactions.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitTautomerQuery.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitFilterCatalog.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitChemReactions.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitGraphMol.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitTautomerQuery.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitFileParsers.dll): $RPATH/boost_iostreams.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?']
```

I'll update `missing_dso_whitelist` as:
```
  missing_dso_whitelist:
    - '*/RDKit*dll'                     # [win]
    - '$RPATH/boost_serialization.dll'  # [win]
    - '$RPATH/boost_iostreams.dll'      # [win]
```

File: recipe/meta.yaml (hunk 1 above)
Comment (skupr-anaconda) [reply recipe/meta.yaml]: @M-Waszkiewicz-Anaconda A new error with `vs2019`:
```
    conda_build.exceptions.OverLinkingError: overlinking check failed

    ['  ERROR (rdkit,Lib/site-packages/rdkit/Chem/Scaffolds/rdScaffoldNetwork.pyd): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitFileParsers.dll): $RPATH/boost_iostreams.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitFilterCatalog.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitmaeparser.dll): $RPATH/boost_iostreams.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitSubstructLibrary.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitScaffoldNetwork.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Lib/site-packages/rdkit/Chem/rdSubstructLibrary.pyd): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitGraphMol.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitScaffoldNetwork.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitmaeparser.dll): $RPATH/boost_iostreams.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitRDStreams.dll): $RPATH/boost_iostreams.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitRDStreams.dll): $RPATH/boost_iostreams.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Lib/site-packages/rdkit/Chem/rdChemReactions.pyd): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitSubstructLibrary.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Lib/site-packages/rdkit/Chem/rdfiltercatalog.pyd): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitChemReactions.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitTautomerQuery.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitFilterCatalog.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitChemReactions.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitGraphMol.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/lib/RDKitTautomerQuery.dll): $RPATH/boost_serialization.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?', '  ERROR (rdkit,Library/bin/RDKitFileParsers.dll): $RPATH/boost_iostreams.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.\n.. is this binary repackaging?']
```

I'll update `missing_dso_whitelist` as:
```
  missing_dso_whitelist:
    - '*/RDKit*dll'                     # [win]
    - '$RPATH/boost_serialization.dll'  # [win]
    - '$RPATH/boost_iostreams.dll'      # [win]
```

File: recipe/meta.yaml [hunk 2]
```diff
@@ -35,40 +35,38 @@ requirements:
     - make                                   # [unix]
     - pkg-config
   host:
-    - boost-cpp                              # [win]
-    - libboost
+    # Boost 1.82 has an issue on Windows: `error C2668: 'boost::hash_value': ambiguous call to overloaded function`,
+    # to avoid this we use Boost 1.73 on Windows.
+    - boost-cpp 1.82
+    - libboost 1.82
```
Comment (M-Waszkiewicz-Anaconda) [inline recipe/meta.yaml]: should we need only one of them boost-cpp or libboost, but not both ?

File: recipe/meta.yaml (hunk 1 above)
Comment (skupr-anaconda) [reply recipe/meta.yaml]: Hmm, it fails to import python modules:
```
Traceback (most recent call last):

  File "C:\b\abs_1fca69bz5t\croot\rdkit_1696328200118\test_tmp\run_test.py", line 8, in <module>

    import rdkit.Chem

  File "C:\b\abs_1fca69bz5t\croot\rdkit_1696328200118\_test_env\lib\site-packages\rdkit\Chem\__init__.py", line 16, in <module>

    from rdkit.Chem import rdchem

ImportError: DLL load failed while importing rdchem: The specified module could not be found.
```

Building the package on `win64` against `libboost/py-boost 1.73` is more reliable but without **py311** support. I would revert my latest changes and I'll build with libboost 1.73

File: recipe/meta.yaml (hunk 2 above)
Comment (skupr-anaconda) [reply recipe/meta.yaml]: Yeah, boost-cpp was required for v1.73 on win but for v1.82 it might be not needed.

Comment (skupr-anaconda) [reply recipe/meta.yaml]: Well, boost-cpp is redundant for v1.82 but `test/imports` are still not working

File: recipe/bld.bat [hunk 3]
```diff
@@ -1,6 +1,9 @@
 REM Change Python header location.
 xcopy %LIBRARY_INC%\boost\python\python.hpp %LIBRARY_INC%\boost
 
+REM `cairo` was needed to generate high-quality PNGs for structure depiction,
+REM see https://www.rdkit.org/docs/Install.html?highlight=cairo#recommended-extras
+REM but we disable it intentionally staring from v2023.03.3
```
Comment (cbouss) [inline recipe/bld.bat:6]: Can you expand on the intention? For our future selves updating this feedstock.

Comment (skupr-anaconda) [reply recipe/bld.bat:6]: @M-Waszkiewicz-Anaconda Could you clarify the real reason for excluding `cairo`?

Comment (M-Waszkiewicz-Anaconda) [reply recipe/bld.bat:6]: that is snowflake requirement to remove  cairo-> libx11 dependency

File: abs.yaml [hunk 4]
```diff
@@ -1,2 +1,4 @@
 upload_channels:
   - sfe1ed40
+channells:
```
Comment (skupr-anaconda) [inline abs.yaml]: @M-Waszkiewicz-Anaconda  `channels` instead of channe**ll**s

File: recipe/build.sh [hunk 5]
```diff
@@ -15,6 +15,9 @@ if [[ "$target_platform" == linux-ppc64le ]]; then
     EXTRA_CMAKE_FLAGS+=" -D PYTHON_NUMPY_INCLUDE_PATH=${SP_DIR}/numpy/core/include"
 fi
 
+# `cairo` was needed to generate high-quality PNGs for structure depiction,
+# see https://www.rdkit.org/docs/Install.html?highlight=cairo#recommended-extras
+# but we disable it intentionally staring from v2023.03.3
```
Comment (JeanChristopheMorinPerso) [inline recipe/build.sh]: I'm not sure to understand why we are disabling cairo... Can you explain a little bit more the intent here?

File: recipe/meta.yaml [hunk 6]
```diff
@@ -9,24 +9,20 @@ package:
...
 build:
   number: 0
   # We skip s390x because it's not supported.
-  skip: True # [s390x]
-  # py-boost hasn't been built for Python 3.11 yet.
-  skip: True # [py<37 or py>310]
+  skip: True # [py<37 or s390x]
   missing_dso_whitelist:
-    - '*/RDKit*dll'  # [win]
+    - '*/RDKit*dll'                     # [win]
```
Comment (JeanChristopheMorinPerso) [inline recipe/meta.yaml]: Isn't it weird that this is whitelisted like this?

File: recipe/build.sh (hunk 5 above)
Comment (M-Waszkiewicz-Anaconda) [reply recipe/build.sh]: that is snowflake requirement to remove cairo-> libx11 dependency

Comment (JeanChristopheMorinPerso) [reply recipe/build.sh]: Thanks. I think this should be added in the comment then.

File: recipe/meta.yaml (hunk 6 above)
Comment (skupr-anaconda) [reply recipe/meta.yaml]: I think it can be related to this https://github.com/AnacondaRecipes/boost-feedstock/pull/16/files#diff-270cf27907bf32793701614a19a54ec06c7dac8f9bd96790c3ee9348ac0ea347R33.
@M-Waszkiewicz-Anaconda Should _*/RDKit*dll_ be removed from `missing_dso_whitelist`  now? Or is there another problem?

Comment (skupr-anaconda) [reply recipe/meta.yaml]: Looking at the logs I can say that the issue was resolved by removing this `missing_dso_whitelist`:
`INFO (rdkit,Library/lib/RDKitTautomerQuery.dll): Library\bin\RDKitMolStandardize.dll found in this package`

**Comment by skupr-anaconda** [comment]
LGTM

**Review by boldorider4 — APPROVED** [review]

**Review by JeanChristopheMorinPerso — APPROVED** [review]
